version: '3'

services:
  app:
    image: felipe070700/whatsapp-manager:01
    ports:
      - "8088:8088"
    # depends_on:
    #   - db
    environment:
      POSTGRES_HOST: 5.161.65.255
      POSTGRES_USER: tecsagroup
      POSTGRES_PASSWORD: tecsagroup
      POSTGRES_DB: postgres_tecsagroup
      POSTGRES_PORT: 5432
    networks:
      - app_network
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
#   postgres:
#     image: postgres:15
#     command: [postgres, --max_connections=100]
#     environment:
#       - POSTGRES_PASSWORD=tecsagroup
#       - POSTGRES_USER=tecsagroup
#       - POSTGRES_DB=postgres_tecsagroup
#     networks:
#       - app_network
#       - traefik_public
#     ports:
#         - 5432:5432
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     deploy:
#       mode: replicated
#       replicas: 1
#       placement:
#         constraints:
#           - node.hostname == worker-postgres
#       resources:
#         limits:
#           cpus: "1"
#           memory: 1024M

# volumes:
#   postgres_data:
#     external: true

networks:
  app_network:
    external: true
  traefik_public:
    external: true