version: '3.7'

services:
  app:
    image: felipe070700/whatsapp-manager
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - evolution_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=evolution_network"
        - "traefik.http.routers.app.rule=Host(`control.shub.tech`)"
        - "traefik.http.routers.app.entrypoints=websecure"
        - "traefik.http.routers.app.priority=1"
        - "traefik.http.routers.app.tls.certresolver=le"
        - "traefik.http.routers.app.service=app"
        - "traefik.http.services.app.loadbalancer.server.port=5000"
  postgres:
    image: postgres:15
    command: [postgres, --max_connections=100]
    environment:
      - POSTGRES_PASSWORD=tecsagroup
      - POSTGRES_USER=tecsagroup
      - POSTGRES_DB=postgres_tecsagroup
    networks:
      - evolution_network
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  postgres_data:
    external: true

networks:
  evolution_network:
    external: true