version: '3'

services:
  app:
    # image: felipe070700/whatsapp-manager:08
    image: golang:1.10-alpine3.7
    container_name: go
    volumes:
      - "./src:/go/src/"
    ports:
      - "80:8088"
    working_dir: /go/src/$whatsapp-swarm-manager-api/
    command: go run main.go
    # ports:
    #   - "8088:8088"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: tecsagroup
      POSTGRES_PASSWORD: tecsagroup
      POSTGRES_DB: postgres_tecsagroup
      POSTGRES_PORT: 5432
    networks:
      - evolution_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
  postgres:
    image: postgres:15
    command: [postgres, --max_connections=100]
    environment:
      - POSTGRES_PASSWORD=tecsagroup
      - POSTGRES_USER=tecsagroup
      - POSTGRES_DB=postgres_tecsagroup
    networks:
      - evolution_network
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  postgres_data:
    external: true

networks:
  evolution_network:
    external: true
