version: "3.8"

services:
  mongo:
    image: mongo:7.0.5
    volumes:
      - portainer_portainer_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - evolution_network
    ports:
      - 27017:27017
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  evolution_network:
    external: true

volumes:
  portainer_portainer_data:
    external: true
  mongodb_config: