name: Docker Build and Push

on:
  push:
    branches:
      - main  # Altere para a branch principal do seu repositório

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t felipe070700/whatsapp-manager:${{ github.sha }} .
        docker push felipe070700/whatsapp-manager:${{ github.sha }}